name: test-gitsign

on: [pull_request]

jobs:
  test_gitsign_action:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    permissions: {}

    name: Install Gitsign and test presence in path
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Install Gitsign
      uses: ./setup-gitsign
    - name: Check install!
      run: gitsign --version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi
      shell: bash
